CanDriver Verification
NittanyMotorsports/Testbench pull request #9
Opened 2024-01-16 19:14 UTC by rks6004

2024-01-16 19:31 UTC, kylegeorge10 requested changes

2024-01-16 19:31 UTC, kylegeorge10 commented on HIL/Drivers/CANDriver.py
> +        os.system('sudo ifconfig can0 down')
Since your asserts are checking that the bus doesn't equal None you should set `self.bus = None` here so that if someone calls `disconnect` and then another function like `write` it won't allow them since the bus communication was closed.

2024-01-16 19:31 UTC, kylegeorge10 commented on HIL/Drivers/CANDriver.py
> +    def connect(self):
We should have the return value of each of these functions defined so for connect it would be `None` here just like `__init__`. For `read` since we are returning the whole message object we should put the return value as `can.Message`. Follow this idea for the remaining functions

2024-01-16 19:31 UTC, kylegeorge10 commented on HIL/Drivers/CANDriver.py
> +# from base_CAN_driver import BaseCANDriver
This line can be deleted since we aren't following this structure anymore

2024-01-16 19:31 UTC, kylegeorge10 commented on HIL/Drivers/CANDriver.py
> +class CANableDriver:
Change the class name to be `CANDriver`

2024-01-16 19:31 UTC, kylegeorge10 commented on HIL/Drivers/CANDriver.py
> +
Put a comment in the same format as the comments under the functions to describe what this is for. Something as simple as `""" Driver for CAN adapter """` should be fine

2024-01-19 00:06 UTC, rks6004 commented on HIL/Drivers/CANDriver.py
> +    def connect(self):
All of these issues resolved in commit #359129ed167932aac37941170fa327f3581921c5

2024-01-19 18:50 UTC, kylegeorge10 commented
LGTM!

2024-01-19 18:51 UTC, kylegeorge10 approved these changes

2024-01-19 18:54 UTC, jdiprato approved these changes
Approved

2024-01-19 18:55 UTC, merged